name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Add missing Babel plugin
      run: npm install --save-dev @babel/plugin-proposal-private-property-in-object

    - name: Run tests
      run: npm test -- --detectOpenHandles